general:
  project_name: fyp_finetune
  saved_models_dir: ./finetune/outputs/saved_models
  gpu_memory_limit: 16
  global_seed: 127

operation_mode: chain_tqe

model:
  # Choose one model type available in Model Zoo for object detection.
  model_type: st_yoloxn
  # For transfer learning from an existing .h5 model, set model_path.
  # model_path: ./external/stm32ai-modelzoo-services/object_detection/pretrained_models/...
  input_shape: (256,256,3)

dataset:
  format: tfs
  dataset_name: fyp_merged
  class_names: [hand, helmet, head, person, tool]
  training_path: ./datasets/fyp_merged/train
  validation_path: ./datasets/fyp_merged/val
  test_path: ./datasets/fyp_merged/test
  quantization_path: ./datasets/fyp_merged/val
  quantization_split: 0.2

preprocessing:
  rescaling:
    scale: 1/255
    offset: 0
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb

data_augmentation:
  random_contrast:
    factor: 0.3
  random_brightness:
    factor: 0.2
  random_flip:
    mode: horizontal
  random_translation:
    width_factor: 0.08
    height_factor: 0.08
  random_rotation:
    factor: 0.04

training:
  batch_size: 32
  epochs: 120
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      patience: 10
    EarlyStopping:
      monitor: val_loss
      patience: 20

postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: true
  max_detection_boxes: 100

quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: ./finetune/outputs/quantized_models

benchmarking:
  board: STM32N6570-DK

mlflow:
  uri: ./finetune/outputs/mlruns

hydra:
  run:
    dir: ./finetune/outputs/experiments/${now:%Y_%m_%d_%H_%M_%S}
