operation_mode: chain_tqe

# ---- General ----------------------------------------------------------------
general:
  project_name: fyp_merged_hand_tool
  saved_models_dir: ./configs/outputs/saved_models
  logger: tensorboard
  global_seed: 127

model:
  framework: torch
  model_type: st_yolod
  model_name: st_yolodv2milli_actrelu_pt
  pretrained: true
  pretrained_dataset: coco
  pretrained_input_shape: [3, 320, 320]
  input_shape: [3, 320, 320]
  num_classes: 2

dataset:
  format: coco
  dataset_name: coco
  class_names: [hand, tool]
  seed: 127
  num_workers: 8
  multiscale_range: 1
  training_path: " "
  train_images_path: ./datasets/fyp_merged/train
  train_annotations_path: ./datasets/fyp_merged/annotations/instances_train.json
  val_images_path: ./datasets/fyp_merged/val
  val_annotations_path: ./datasets/fyp_merged/annotations/instances_val.json
  test_images_path: ./datasets/fyp_merged/test
  test_annotations_path: ./datasets/fyp_merged/annotations/instances_test.json
  quantization_split: 1
  quantization_path: ./datasets/fyp_merged/val
  mosaic_prob: 0.4
  mixup_prob: 0.0
  hsv_prob: 0.8
  flip_prob: 0.5
  degrees: 2.0
  translate: 0.03
  mosaic_scale: (0.8, 1.2)
  enable_mixup: false
  mixup_scale: (1.0, 1.0)
  shear: 0.5

training:
  trainer_name: yolod
  batch_size: 24
  warmup_epochs: 3
  epochs: 260
  scheduler: yoloxwarmcos
  no_aug_epochs: 35
  ema: true
  print_interval: 1
  eval_interval: 1
  save_history_ckpt: true
  optimizer:
    AdamW:
      learning_rate: 0.0007
      warmup_lr: 0.0
      min_lr_ratio: 0.05
      weight_decay: 5.0e-4
  resume_training_from: ''
  start_epoch: 0
  fp16: true

# ---- Preprocessing ----------------------------------------------------------
preprocessing:
  rescaling:
    scale: 1
    offset: 0
  mean: [127, 127, 127]
  std: 128.0
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

# ---- Postprocessing ---------------------------------------------------------
postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: true
  max_detection_boxes: 100

# ---- Quantization -----------------------------------------------------------
quantization:
  quantizer: onnx_quantizer
  target_opset: 17
  granularity: per_channel
  quantization_type: PTQ
  quantization_input_type: float
  quantization_output_type: float
  export_dir: ./configs/outputs/quantized_models

# ---- Experiment tracking ----------------------------------------------------
mlflow:
  uri: ./configs/outputs/mlruns

hydra:
  run:
    dir: ./configs/outputs/experiments/${now:%Y_%m_%d_%H_%M_%S}
