dataset:
  format: pascal_voc_format
  class_names: [hand, tool]
  dataset_name: fyp_merged
  training_path: ./datasets/fyp_merged/train
  validation_path: ./datasets/fyp_merged/val
  test_path: ./datasets/fyp_merged/test
  dataset_path: ./datasets/fyp_merged/train

pascal_voc_format:
  images_path: ./datasets/_unused_st_converter/images
  xml_files_path: ./datasets/_unused_st_converter/xml
  export_dir: ./datasets/_unused_st_converter/export

settings:
  max_detections: 100
  exclude_unlabeled_images: false
  max_percentage_filtered: 1

hydra:
  run:
    dir: ./configs/outputs/dataset/${now:%Y_%m_%d_%H_%M_%S}
