model:
  name: tinyissimoyolo_v8_192
  uc: od_coco-person
  model_path: null  # injected by run_quantize.py
  input_shape: [192, 192, 3]

quantization:
  fake: false
  quantization_type: per_channel
  quantization_input_type: uint8
  quantization_output_type: float
  calib_dataset_path: null  # injected by run_quantize.py
  export_path: null  # injected by run_quantize.py

pre_processing:
  rescaling: { scale: 255, offset: 0 }
